import { AVATAR_CONFIG } from './constants'

// Simple in-memory cache for avatars (max 100 entries)
const avatarCache = new Map<string, string>()
const MAX_CACHE_SIZE = 100

/**
 * Generates a URL for an autogenerated avatar with caching
 * @param name - The name to generate avatar from
 * @param size - The size of the avatar in pixels
 * @returns The avatar URL
 */
export function generateAvatarUrl(name: string, size: number = AVATAR_CONFIG.defaultSize): string {
  const cacheKey = `${name}-${size}`

  // Return cached URL if available
  if (avatarCache.has(cacheKey)) {
    return avatarCache.get(cacheKey)!
  }

  const encodedName = encodeURIComponent(name)
  const params = new URLSearchParams({
    name: encodedName,
    size: size.toString(),
    background: AVATAR_CONFIG.options.background,
    color: AVATAR_CONFIG.options.color,
    bold: AVATAR_CONFIG.options.bold.toString(),
    format: AVATAR_CONFIG.options.format,
  })

  const url = `${AVATAR_CONFIG.baseUrl}?${params.toString()}`

  // Cache the URL (with size limit)
  if (avatarCache.size >= MAX_CACHE_SIZE) {
    const firstKey = avatarCache.keys().next().value
    if (firstKey) {
      avatarCache.delete(firstKey)
    }
  }
  avatarCache.set(cacheKey, url)

  return url
}

/**
 * Generates avatar props for shadcn/ui Avatar component
 * @param name - The name to generate avatar from
 * @param size - The size of the avatar in pixels
 * @returns Avatar props object
 */
export function getAvatarProps(name: string, size: number = AVATAR_CONFIG.defaultSize) {
  return {
    src: generateAvatarUrl(name, size),
    alt: name,
    className: `h-${size / 4} w-${size / 4}`, // Convert pixels to Tailwind units
  }
}
