'use client'

import React, { type FC } from 'react'

import { Home } from 'lucide-react'
import Link from 'next/link'

import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@/components/ui/breadcrumb'
import { cn } from '@/utilities/cn'

import type { BreadcrumbItem as BreadcrumbItemType } from '@/types/breadcrumb'

type PostBreadcrumbProps = {
  breadcrumbItems: BreadcrumbItemType[]
  className?: string
  separatorClassName?: string
  pageClassName?: string
  linkClassName?: string
}

/**
 * Reusable breadcrumb component for post pages
 * Accepts breadcrumbItems generated by generateBreadcrumb utility
 * Supports custom styling for different post styles
 */
export const PostBreadcrumb: FC<PostBreadcrumbProps> = ({
  breadcrumbItems,
  className,
  separatorClassName,
  pageClassName,
  linkClassName,
}) => {
  if (!breadcrumbItems || breadcrumbItems.length === 0) {
    return null
  }

  return (
    <div className='w-full overflow-x-auto -mx-4 px-4 sm:mx-0 sm:px-0'>
      <Breadcrumb className={className}>
        <BreadcrumbList className='flex-nowrap min-w-max'>
          {breadcrumbItems.map((item, index) => (
            <React.Fragment key={`breadcrumb-${index}`}>
              <BreadcrumbItem className='flex-shrink-0'>
                {item.isCurrent ? (
                  <BreadcrumbPage
                    className={cn('truncate max-w-[150px] sm:max-w-none', pageClassName)}
                  >
                    {item.label}
                  </BreadcrumbPage>
                ) : (
                  <BreadcrumbLink href={item.url || '/'} asChild>
                    <Link
                      href={item.url || '/'}
                      className={cn(
                        'truncate max-w-[120px] sm:max-w-none inline-flex items-center gap-1',
                        linkClassName,
                      )}
                    >
                      {item.isHome ? <Home className='w-4 h-4 flex-shrink-0' /> : item.label}
                    </Link>
                  </BreadcrumbLink>
                )}
              </BreadcrumbItem>
              {index < breadcrumbItems.length - 1 && (
                <BreadcrumbSeparator className={cn('flex-shrink-0', separatorClassName)}>
                  <span className='mx-1.5'>/</span>
                </BreadcrumbSeparator>
              )}
            </React.Fragment>
          ))}
        </BreadcrumbList>
      </Breadcrumb>
    </div>
  )
}
